version: '3.9'

services:
  event:
    container_name: event
    build:
      context: ../
      dockerfile: ./docker/event/Dockerfile
    image: event
    restart: always
    tty: true
    expose:
      - '8001:8001'
    ports:
      - '8001:8001'
    networks:
      - api
    depends_on:
      - auth
      - event-db
  migrator:
    container_name: migrations
    build:
      context: ../
      dockerfile: ./docker/migrator/Dockerfile
    tty: true
    restart: always
    networks:
      - api
    depends_on:
      - auth-db
      - event-db
  event-db:
    image: postgres:15.4-alpine
    container_name: event-db
    restart: always
    tty: true
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event
    expose:
      - '5432:5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres-event:/var/lib/postgresql/data
    networks:
      - api

  keydb:
    container_name: auth-keydb
    image: eqalpha/keydb:latest
    restart: always
    tty: true
    volumes:
      - keydb:/data
    expose:
      - '6379:6379'
    ports:
      - '6379:6379'
    command:
     - '--requirepass auth'
    networks:
      - api

volumes:
  postgres-auth:
    driver: local
  postgres-event:
    driver: local
  keydb:
    driver: local


networks:
  api:
    driver: bridge
